### ISSUE TITLE
WHERE IS YOUR ONION SITE HOSTED?

### ISSUE THREAD

**Issue by luckypoem** [JamieOnUbuntu/jamieweb#2]
hi.
i saw ur site: http://jamiewebgbelqfno.onion/ and http://jamie3vkiwibfiwucd6vxijskbhpjdyajmzeor4mc4i7yopvpo4p7cyd.onion/blog/ ,
i wonder WHERE IS YOUR ONION SITE HOSTED?
tks a lot.

**Comment by JamieOnUbuntu** [comment]
Hi @luckypoem,

My Onion Hidden Services are hosted by myself on a server running Tor.

I actually have written a couple of blog posts about setting these up, [here](https://www.jamieweb.net/blog/tor-hidden-service/) and [here](https://www.jamieweb.net/blog/onionv3-hidden-service/).

It's pretty easy to set up your own on a Linux system, if you're using a Debian-based distro, make sure you don't use the built-in Tor packages as they are often out of date. You must add the official Tor repositories and install it from there as these are properly maintained.

Hope this helps.

Thanks,
Jamie
